backend:
  name: github
  repo: edm00se/blog
  branch: next

media_folder: "content/posts/images" # Media files will be stored in the repo under content/posts/images
public_folder: "./images" # The src attribute for uploaded media will begin with ./images
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'md'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Name, name: name, widget: string, default: "tag"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - label: "Category"
        name: "tags"
        widget: "select"
        field: {label: Name, name: name, widget: string, default: "category"}
      - {label: "Canonical URL", name: "canonical_url", widget: "boolean", required: true, default: false}
      - {label: "Permalink", name: "permalink", widget: string, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
